### ISSUE TITLE
crash when downloading file.JPG

### ISSUE THREAD

**Issue by Pazuu** [syncthing/syncthing-lite#107]
The app crashes when i download a file.JPG (file.jpg works just fine).
I send a crash report via Google play.

**Comment by l-jonas** [comment]
@Pazuu Are you sure that it's caused by that? On my device, it does not make a difference.

@Nutomic I will send a mail to <https://github.com/syncthing/syncthing-lite/blob/master/app/src/main/play/contactEmail> for the crash report access.

**Comment by l-jonas** [comment]
@Nutomic Couldn't send the mail, got a bounce:

> 577 5.1.1 <removed@removed.com>: Recipient address rejected: undeliverable address: mail for removed.com loops back to myself

**Comment by Pazuu** [comment]
I tested it by renaming the file, but i may overlook something. I hope the report helps. Thanks!!

**Comment by Nutomic** [comment]
@l-jonas Sorry I guess that email isn't going anywhere. Send it to me at nutomic com instead.

**Comment by l-jonas** [comment]
@Nutomic Did it. But don't forget to fix it as it is the mail address which is shown in the play store entry. (no one cares, except Google and their rules for the play store).

@Pazuu I renamed my test file too (and it still worked), but it could depend on the environment (Android version, other installed Apps, ...). Did you wait until the new file name showed up in Syncthing Lite?

**Comment by Pazuu** [comment]
Yes i waited until syncthing lite showed the new name. I will test it again! :smiley_cat:

I am on Android 7.1.2 on a fairphone 2.

**Comment by Nutomic** [comment]
@l-jonas I don't want to take care of the emails. If you want, I can forward them to you (I think that also includes mails for syncthing-android).

**Comment by l-jonas** [comment]
@Pazuu I couldn't find a crash report from a fairphone. Is it eventually the gallery app which crashed? Otherwise: Please test it again, send a report and tell me the time at which you sent it.

**Comment by l-jonas** [comment]
This could be related to <https://github.com/syncthing/syncthing-lite/pull/114> (but then the fix would only fix the crash, it would still be not possible to open the file)

**Comment by Pazuu** [comment]
With version 0.3.8 the crash is gone! :smiley_cat:  
Its just, that the app opens a file.jpg with the gallery app, but asks me which app to open file.JPG. It then offers me apps to open that file.JPG with, but the gallery app is not within the offered apps. I experience the same with some file.pdf files. 
But as i can use the "save as" function, i am still able to access these files.

Thank you for fixing the crash! It is getting more and more fun to use the app!  :balloon:

**Comment by l-jonas** [comment]
Well, then <https://github.com/syncthing/syncthing-lite/pull/127> could help you (it's disabled by default and must be enabled in the settings)
