### ISSUE TITLE
Don't share folders with all known devices

### ISSUE THREAD

**Issue by lapo-luchini** [syncthing/syncthing-lite#17]
I added two devices, let's say A and B, the first offers the directory Apples the second offers the directory Bananas; on A I got a pop-up asking if I want to accept directory Apples from (mobile device running Lite version).
I didn't check the internals of the protocol, is this expected?

**Comment by Nutomic** [comment]
See this issue that you opened yourself a year ago ;)

https://github.com/davide-imbriaco/a-sync-browser/issues/4

**Comment by lapo-luchini** [comment]
Ehm, sorry, memory can be fickle. 😅

**Comment by steveeJ** [comment]
Adding some details that I'm encountering:
* the folder that is shared back by the syncthing-lite client has a folder-id that equals the folder-name.
* clicking "later" on the share request will immediately bring the request back. Are we supposed to actually add this shrea?

**Comment by Nutomic** [comment]
No, you can ignore that folder. Its just that the library doesnt yet support selective sharing of folders, so every folder is shared with every device.

**Comment by l-jonas** [comment]
There are two options for this:

1. Only tell a device about a folder when the device told this App about it (save it locally) - problem: Knowing a folder id is enough to trick this App to eventually do file uploads to this device
2. Add a UI to select devices for folders, accept the first device which shares a folder automatically
