### ISSUE TITLE
Doesn't display my folders 

### ISSUE THREAD

**Issue by beckysophie** [syncthing/syncthing-lite#28]
***Expected Behavior***
The app should load and show folders that are on my device so as to use them carry out what the app was created for 

***Actual Behavior***

It doesn't load any file on my device. Showing 'No folders available'

***How to produce the bug***

Just open the app and wait for it to load 

                 ***Device Info***

* Operating system : Android 6.0
* Phone : Infinix hot s
* Syncthing Lite App

***Recording of the bug is showned below......***

Watch the video below to see how it behaves.... 

https://youtu.be/Pa13WCuLz10

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/doesn-t-display-my-folders">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Nutomic** [comment]
Did you connect syncthing lite to another Syncthing device, and share a folder from that device to syncthing lite? And are your devices shown as connected?

**Comment by CristianFranceschet** [comment]
Good evening,
I have the same issue: "no folder available" (Samsung Galaxy S6, Android 7.0)
I added my phone to a Syncthing introducer and shared a folder, but it never connected.
Thank you!

**Comment by yeus** [comment]
Hi,
same issue here also. Added the ids on both sides but no folders displaying, I am using syncthing version 0.14.44 on the computer side and most up-to-date from google play store with a "homtom S8" phone on android 7.0.

let me know if I can do any further "investigations"

**Comment by hackel** [comment]
This happened to me after I killed syncthing-lite and cleared the app cache.  Apparently it takes a while to re-sync the file list once it is restarted.  Eventually, it did do so on its own and I can again see all of my files and folders in syncthing-lite.

**Comment by Cecchellone** [comment]
same issue here, no folder available and the device has never connected to the others...

**Comment by whoamin** [comment]
same for me. useless

**Comment by l-jonas** [comment]
The last comment here is from a time at which the last app version was 0.2.1 which is from february 2018. It is very likely that this issue does not occur anymore so that it is closed now.
