### ISSUE TITLE
Wait for translations

### ISSUE THREAD

**Issue by licaon-kter** [syncthing/syncthing-lite#31]
While it's great that you've just pushed a new version, the builds will not be translated and your release schedule makes it so the app will get translated in March or so.

It would be nicer to first push the new strings to Transifex, wait a day or two for translators to be notified and get a chance to update them, and them publish the tag/release.

Thanks

**Comment by Nutomic** [comment]
I'm not sure what would be the best way to handle translations. Even now, 3 out of 5 languages are only halfway translated.

**Comment by licaon-kter** [comment]
There's that too, indeed. :(
