### ISSUE TITLE
Sync directories

### ISSUE THREAD

**Issue by mcladyz** [syncthing/syncthing-lite#36]
It would be great if it was possible to sync directories inside folders in addition to files.

Example: There is a top-level folder "Music" and the user only wants to download a certain album from a certain artist. The dir hierarcy looks like this: Music -> BandX -> [AlbumA, AlbumB, AlbumC]

Related to #34, but not the same feature request.

**Comment by AudriusButkevicius** [comment]
It is the same request, as the two are talking pretty much about the same thing.
