### ISSUE TITLE
Please merge new translations

### ISSUE THREAD

**Issue by jony0008** [syncthing/syncthing-lite#38]
Please release a new version with the new translations from Transifex.

**Comment by Nutomic** [comment]
@l-jonas Just noticed that we forgot this for the last release. There are scripts `prepare-release.bash` and `publish-release.bash` which take care of translations automatically, among other things. You just need to install the [transifex client](https://github.com/transifex/transifex-client) and configure it with your Transifex account (I probably need to add you as a maintainer on Transifex as well).

**Comment by l-jonas** [comment]
@Nutomic I've sent a join request at transifex (I can't access anything except the overview at transifex and the client tells me that I don't have got the permissionn).

**Comment by Nutomic** [comment]
Okay I added you as a maintainer.
