### ISSUE TITLE
Can't connect to devices. TLS handshake: EOF/illegal parameter

### ISSUE THREAD

**Issue by ImPat** [syncthing/syncthing-lite#6]
There's no description telling the user what to do. I added a device and at first it showed up red. After 1-2 minutes(!) it showed up green. I tried updating the index to see if I can get my folders to show up, but I get an error. There were also no connection attempts showing up at the syncthing "server" on my windows machine. Do I have to install a special software on my pc? What am I doing wrong? A bit of documentation can't hurt.

**Comment by Nutomic** [comment]
So this is how it's supposed to work:

1. add a device on your phone using device id or qr code
2. accept phone on your other device in Syncthing
3. share folder to your phone

However, there are some cases where connections might not work:
- if syncthing-android is running (you have to stop that app first)
- i've only really tested local discovery connections, global discovery and relays might still have bugs

**Comment by ImPat** [comment]
Unfortunately, I've been unable to get this to work. Here are some errors I received on the Server when running this on my phone(local network), and an android emulator(maybe behind nat).

```
[Redacted] 2017/12/27 18:52:55.378217 tcp_listen.go:103: DEBUG: Listen (BEP/tcp): connect from 192.168.My.Phone:52096
[Redacted] 2017/12/27 18:52:55.382246 tcp_listen.go:117: INFO: Listen (BEP/tcp): TLS handshake: EOF
```

```
[Redacted] 2017/12/27 18:52:57.890106 relay_listen.go:88: DEBUG: Listen (BEP/relay): setting traffic class: operation not supported
[Redacted] 2017/12/27 18:52:59.244697 relay_listen.go:101: INFO: Listen (BEP/relay): TLS handshake: remote error: tls: illegal parameter
```
I've not recieved a syncthing connection request from any of the devices I tested. Normal Syncthing was not running on my phone or the emulator.

**Comment by ImPat** [comment]
Any update on this? Does it work correctly when you run it? What's your setup(Syncthing Version, android version and oem)?

**Comment by Nutomic** [comment]
The networking code in the library is pretty complicated, so this will take some time to fix. I'm testing on Cyanogenmod 6, and with the latest Syncthing release as peer. But I'm also getting some errors. Keep in mind that this is still in alpha state.

**Comment by kiyoon** [comment]
I have the same symptom. I added 2 devices but couldn't get any acceptance confirmation message. I also have TLS illegal parameter error. I'm using Galaxy Note 5 and the other 2 devices are Windows and Linux.

**Comment by lovenemesis** [comment]
I'm using several Sony Xperia devices running on Android 7.1.1. None of them are able to connect the syncthing instance running on two RPi2 0.14.42 inside local network.

This app really has potential for mobile platform. Keep up the good work!

Thanks,

**Comment by ImPat** [comment]
Didn't @imsodin talk about updating the BEP protocol [here?](https://forum.syncthing.net/t/new-android-app-syncthing-lite/11086/5) His repo doesn't have any commits though.

**Comment by imsodin** [comment]
@ImPat My changes have nothing to do with this issue, but you're right, I should make them accessible even if I stopped trying to understand Android building for the moment and it's thus untested: nutomic/syncthing-java#7

**Comment by Nutomic** [comment]
This bug is fixed in 0.2.0 (there was a problem where the app would try to open multiple connections to the same device).

**Comment by Bruceforce** [comment]
Is it really fixed?

I just clean installed 0.2.0 via play store and tried to connect to my NAS (via LAN), but the NAS still logs

```
2018-02-08 01:17:22 Listen (BEP/tcp): TLS handshake: remote error: tls: illegal parameter
2018-02-08 01:17:45 Listen (BEP/tcp): TLS handshake: EOF
```

**Comment by Nutomic** [comment]
@Bruceforce Can you make sure that Syncthing on the NAS does not show Syncthing Lite as connected before you start the app? Were you doing anything (eg upload or download files) when this happened?

**Comment by Bruceforce** [comment]
To show syncthing lite as connected it must be added as new device on the NAS first or did I misunderstand you? But I can't even add it on the NAS. As soon as I start syncthing lite, the NAS begins to log the aforementioned errors and I'm not able to even add the syncthing lite device.

I wasn't doing anything while this happened. The NAS was connected to one other node, but both were idle. 

Some questions: I don't have to uninstall the normal syncthing do I (Stopping it on the Android side is still sufficient)?
Is it okay if normal syncthing on Android is in the NAS device list as long as the normal app is stopped or do I have to unpair both?

**Comment by Nutomic** [comment]
So you are not receiving a notification to add the Syncthing Lite device on the NAS? You only need to stop Syncthing Android, no need to uninstall or disconnect. 

Can you post a log from the Android side?

**Comment by Bruceforce** [comment]
Yes, I'm not receiving a notification to add the syncthing lite device on my NAS.

Does this help you (if not - sorry, I've never collected logs from Android before)?
https://gist.github.com/Bruceforce/6101e0a0294bcafe05a9a0744c1dd29d

**Comment by lapo-luchini** [comment]
BTW: I only receive rarely the notifications server-side, that's why I asked #14.

**Comment by 3v1n0** [comment]
I'm getting the very same issue logged by @Bruteforce, here's with a LG G5 SE.

Unfortunately the app isn't usable :-(.
I've also installed the default client, but that's not running.

**Comment by skerit** [comment]
Only local connections seem to work, any device over the internet fails to connect.

**Comment by clawoflight** [comment]
I also cannot connect over the internet. I have KDE connect for LAN, so this is a deal-breaker for me.

**Comment by stephenjamieson** [comment]
same issue, doesn't work. Project dead?

**Comment by l-jonas** [comment]
The missing support for connecting over the internet was fixed with <https://github.com/syncthing/syncthing-java/pull/10>, but this is not yet part of the Android App.
