### ISSUE TITLE
update version on google play

### ISSUE THREAD

**Issue by xgdgsc** [syncthing/syncthing-lite#66]
google play version is still at 0.2.1

**Comment by Nutomic** [comment]
@AudriusButkevicius did you get my last mail about the build server?

**Comment by AudriusButkevicius** [comment]
In that chain, it seems I am the last one that replied.

**Comment by Nutomic** [comment]
Weird, I re-sent it now.

**Comment by Pazuu** [comment]
I am on 0.3.1 now, thanks! :balloon:
