### ISSUE TITLE
feature request: Save a file in downloads folder

### ISSUE THREAD

**Issue by Pazuu** [syncthing/syncthing-lite#75]
At some point it would be nice to be able to download a file e.g. in the downloads folder. 
Right now downloaded files in the cache are hard to find and have cryptic names.

Thank you for investing so much time, i love this app!

**Comment by l-jonas** [comment]
@Pazuu You can currently open the files using your system native files apps at newer Android versions. For "downloading" files: I think an entry in the context menu of the file entries could help. Would the use case be to download bigger files/ download files in the background (or should that be an other option)? Would using the "save as" system dialog fit better to allow saving it directly in other directories too.

**Comment by Pazuu** [comment]
I was not thinking of downloading bigger files in the background, but of a solution like using the "save as" system dialog to allow saving a file directly in other directories. Right now if i click on a .jpg file, my standard gallery app opens the file, and if i share it (using the share function of the galery app) the name of the file is the cryptic name (as in the cache).
I think it could be useful to be able to download a file, edit it with different apps, and then share it. :)

**Comment by l-jonas** [comment]
@Pazuu It think that it is possible to show the correct name for files in other Apps. I created an issue for it at <https://github.com/syncthing/syncthing-lite/issues/76>.

For the save as: I would prefer to do the normal download process and replace the opening of the file at the end with copying it to the specified location. This would keep the caching, but takes the double space on disk if save as is used.

**Comment by Pazuu** [comment]
Thanks I-jonas for your work!! That sounds great!
