### ISSUE TITLE
Encrypt App data with a passphrase

### ISSUE THREAD

**Issue by Pazuu** [syncthing/syncthing-lite#85]
I would like to share the thought that it could feel better to be able to encrypt the apps content (index, cache, filenames, access to files) with a strong passphrase. Especially when i use the app to access large amounts of private data with an old android phone that is likely to be lost (while turned on). I know that if ever this would be a long-term goal. :)

**Comment by l-jonas** [comment]
@Pazuu I don't want to be unpolite, but Android has got a built in encryption feature (If someone who finds the phone is able to read the encryption key from the RAM, then he likely has got better ways to get your data). And if the phone is old (assuming no security updates), than it's generally unsafe and it is possible that an attacker gets your passphrase when you enter it.

Encrypting the database (file list) and config file (contains the device key) is possible. Encrypting cached data is possible too, but this would make it necessary to create an unencrypted copy of it to open a cached/ downloaded file with other Apps.

For the device lost scenario: It's easy to revoke the access permission for the phone. But the cached files are already at the phone in this case (but I assume that this are not all files, but if the files are really private, I would not put them on my phone at all).

**Comment by Pazuu** [comment]
That is absolutly no unpolite response! Thanks for taking time for this thorough answer. And i got that the effort is out of all proportion to an additional gain in security. I think i just have to reevaluate the level of access i want my phone to have to my documents. :o)
