### ISSUE TITLE
syncthing-lite device is shown as syncing 0% in all other syncthing instances

### ISSUE THREAD

**Issue by simonvanderveldt** [syncthing/syncthing-lite#86]
On the other devices I've connected syncthing-lite to the syncthing-lite device is show as 0% synced. I'm also unable to download any files using synthing-lite.

Is there any way I can get some more info/logging what's happening/why it isn't working?

**Comment by l-jonas** [comment]
@simonvanderveldt It is expected that the sync progress keeps at 0% because files are only transfered when they are requested. Is the device shown as connected (green icon) in the device list in syncthing lite. Are the folders and their contents shown in syncthing-lite? Do you know how to use ADB?

**Comment by l-jonas** [comment]
@simonvanderveldt Yes, it's green. Showing the status (or better, the IP address) as text would be better; I added this to <https://github.com/syncthing/syncthing-lite/issues/44>. 

After launching Syncthing Lite, you have to wait a moment (technically, it always takes more than 5 seconds currently, when using a relay it takes a bit longer (I would guess 30 seconds)). The connection is kept for one minute when the App is not removed from the recent app list.

The local and global discovery is always enabled in Syncthing Lite (you can't configure it except changing the global discovery servers in the config file). 

The thing in the Reamde only applies when not using local discovery connections. It occurs if you kill the App by removing it from the recent App list or the connection is lost by other causes.

**Comment by l-jonas** [comment]
As the question has been answered and the 0% were documented, I close this now
