### ISSUE TITLE
Welcome Screen doesn't detect any folders

### ISSUE THREAD

**Issue by yeus** [syncthing/syncthing-lite#99]
When going through the welcome wizard, the waiting icon for folders (third screen in the wizard) just stays there until the app crashes after a couple seconds.

I am using a Huawei P smart with Android 8.0.0

Is there any way how I can help debugging this problem?

**Comment by l-jonas** [comment]
@yeus Depends on your knowledge. "adb logcat" allows you to get a crash report. Or you send it using Google Play and Nutomic posts it here.

**Comment by l-jonas** [comment]
I am closing this issue now because there aren't any details which help fixing it. If it still occurs, please create a new issue with a crash report (or send one using Google Play and write that into the description).
